@host = http://localhost:5204

### Get hello world
GET {{host}}/

### Minimal: get all games
GET {{host}}/games

### Minimal: get game by id
GET {{host}}/games/1

### Minimal: create a game
POST {{host}}/games
Content-Type: application/json

{
  "name": "Hollow Knight",
  "genre": "Metroidvania",
  "price": 14.99,
  "releaseDate": "2017-02-24"
}

### MVC: get all games
GET {{host}}/api/Games

### MVC: update a game
PUT {{host}}/api/Games/1
Content-Type: application/json

{
  "name": "Spacewar Deluxe",
  "genre": "Action",
  "price": 4.99,
  "releaseDate": "1962-10-19"
}

### Minimal: delete a game
DELETE {{host}}/games/1